workspace 'WGVisitorDemo IOS'
platform :ios, '8.0'

#inhibit_all_warnings!


source 'https://github.com/LiveAdminsLLC/PodSpecs.git'

source 'https://github.com/CocoaPods/Specs.git'

project 'Demo'

target "DemoSwift" do
    
use_frameworks!


pod 'WGVisitorSDK', :path => '../WGSDK/'

pod 'SignalR-ObjC', :path => '../WGSDK/SignalR-ObjC/'




pod 'Fabric'
pod 'Crashlytics'


end
